### ISSUE TITLE
Autojoin failures

### ISSUE THREAD

**Issue by ara4n** [tdfischer/pto#1]
Firstly, **THIS IS SO COOL!!!!** :D :D :D

In other news, here are a few random observations and an actual bug (i think):

1. It wasn't clear that you have to hand it the full CS API path as the arg (with trailing slash).  Sorry if I've missed this somewhere in the readme.  Also, sorry that I don't have enough rust fu yet to improve the commandline params: `$ target/debug/pto http://127.0.0.1:8008/_matrix/client/r0/`

2. If /login fails, it probably shouldn't be trying to /initialSync

3. It should probably be calling /sync rather than /initialSync and /events - /sync is much simpler (albeit slghtly less performant on synapse currently)

4. It seems to be using your IRC nickname to form the matrix ID.  I'd expect it to be using your IRC username, given IRC username/password form an auth tuple, not IRC nick/pass?

5. It crashed after I tried to join an existing alias with /join #test:sierra and then said something - unsure if this is meant to work, but how else would you join a room?  Or should I have already been joined to my current rooms?

```
Got a message! Message { prefix: None, command: Join, args: ["#test:sierra"], suffix: None }
Got a message! Message { prefix: None, command: Mode, args: ["#test:sierra"], suffix: None }
unhandled Message { prefix: None, command: Mode, args: ["#test:sierra"], suffix: None }
Got a message! Message { prefix: None, command: Unknown("WHO"), args: ["#test:sierra"], suffix: None }
unhandled Message { prefix: None, command: Unknown("WHO"), args: ["#test:sierra"], suffix: None }
Response! Object({"chunk": Array([]), "end": String("s625_1_0_336_17"), "start": String("s625_1_0_336_17")})
Got message from matrix! EndPoll
Got a message! Message { prefix: None, command: Privmsg, args: ["#test:sierra"], suffix: Some("oh, hello!") }
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
stack backtrace:
   1:        0x10e3f25e8 - sys::backtrace::tracing::imp::write::h71b7c99a21cff148fMt
   2:        0x10e3f3e7f - panicking::log_panic::_<closure>::closure.40876
   3:        0x10e3f3922 - panicking::log_panic::h2d79dd1ccae87ed8BFx
   4:        0x10e3e7f86 - sys_common::unwind::begin_unwind_inner::hb8ac08b8a72b9d1bhPs
   5:        0x10e3e836e - sys_common::unwind::begin_unwind_fmt::h076ba7ed08690e9dnOs
   6:        0x10e3f1c07 - rust_begin_unwind
   7:        0x10e414ba0 - panicking::panic_fmt::h3967afc085fe8067LFK
   8:        0x10e414e9c - panicking::panic::h77d028a733b1a80eiEK
   9:        0x10e2ecd20 - option::_<impl>::unwrap::unwrap::h2810581680306710898
  10:        0x10e2ec5dc - bridge::_<impl>::room_from_irc::hcfcb80b7ecf6094aYDb
  11:        0x10e2e05b1 - bridge::_<impl>::handle_client::hc6c6b5c0397a1be0fJb
  12:        0x10e2dfa4b - bridge::_<impl>::ready::h59baa2ae828533b8Srb
  13:        0x10e2f1ed3 - event_loop::_<impl>::io_event::io_event::h15634235306661863128
  14:        0x10e2f1e09 - event_loop::_<impl>::io_process::io_process::h1342774954010894461
  15:        0x10e2f162b - event_loop::_<impl>::run_once::run_once::h9126862583228278158
  16:        0x10e2f0fab - event_loop::_<impl>::run::run::h5498248675409789505
  17:        0x10e2a4e89 - bridge::_<impl>::run::h40d98acb1854b752bFb
  18:        0x10e2a4955 - _<impl>::ready::_<closure>::closure.10883
  19:        0x10e2a4393 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.10782
  20:        0x10e2a4308 - sys_common::unwind::try::try_fn::try_fn::h5784654456480655777
  21:        0x10e3f1a28 - __rust_try
  22:        0x10e3ef84e - sys_common::unwind::try::inner_try::h65d1cf17926a7a9aPLs
  23:        0x10e2a4245 - sys_common::unwind::try::try::h14779548576051911258
  24:        0x10e2a407e - std::thread::_<impl>::spawn::_<closure>::closure.10757
  25:        0x10e2a4bf7 - boxed::_<impl>::call_box::call_box::h16152174961385334756
  26:        0x10e3f324d - sys::thread::_<impl>::new::thread_start::h6c3076098329c459IZw
  27:     0x7fff95e45267 - _pthread_body
  28:     0x7fff95e451e4 - _pthread_start
Response! Object({"chunk": Array([]), "end": String("s625_1_0_336_17"), "start": String("s625_1_0_336_17")})
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotifyError::Closed(..)', ../src/libcore/result.rs:741
stack backtrace:
   1:        0x10e3f25e8 - sys::backtrace::tracing::imp::write::h71b7c99a21cff148fMt
   2:        0x10e3f3e7f - panicking::log_panic::_<closure>::closure.40876
   3:        0x10e3f3922 - panicking::log_panic::h2d79dd1ccae87ed8BFx
   4:        0x10e3e7f86 - sys_common::unwind::begin_unwind_inner::hb8ac08b8a72b9d1bhPs
   5:        0x10e3e836e - sys_common::unwind::begin_unwind_fmt::h076ba7ed08690e9dnOs
   6:        0x10e3f1c07 - rust_begin_unwind
   7:        0x10e414ba0 - panicking::panic_fmt::h3967afc085fe8067LFK
   8:        0x10e2fa8ce - result::_<impl>::unwrap::unwrap::h5364017936492151894
   9:        0x10e2f9de1 - bridge::_<impl>::poll_matrix::_<closure>::_<closure>::closure.14643
  10:        0x10e2f9933 - result::_<impl>::and_then::and_then::h6154261532790941551
  11:        0x10e2f9209 - bridge::_<impl>::poll_matrix::_<closure>::closure.14624
  12:        0x10e2f8b91 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.14613
  13:        0x10e2f8af8 - sys_common::unwind::try::try_fn::try_fn::h4191680235686461962
  14:        0x10e3f1a28 - __rust_try
  15:        0x10e3ef84e - sys_common::unwind::try::inner_try::h65d1cf17926a7a9aPLs
  16:        0x10e2f8a35 - sys_common::unwind::try::try::h463394110065254697
  17:        0x10e2f8797 - std::thread::_<impl>::spawn::_<closure>::closure.14609
  18:        0x10e2f97e7 - boxed::_<impl>::call_box::call_box::h14992849548689379974
  19:        0x10e3f324d - sys::thread::_<impl>::new::thread_start::h6c3076098329c459IZw
  20:     0x7fff95e45267 - _pthread_body
  21:     0x7fff95e451e4 - _pthread_start
```

**Comment by ara4n** [comment]
(it also panics similarly if I try to `/join #test`).

**Comment by tdfischer** [comment]
Thanks for the report! And the words of encouragement!

The ``JOIN`` command currently is unsupported though in theory it shouldn't actually panic.

It should be using the value from the ``USER`` command sent when connecting as part of the username/password to login to matrix. I should also note that the IRC parser doesn't completely adhere to the IRC specification yet so it is more likely grabbing the wrong field than explicitly trying to use your nickname. Ref: https://github.com/tdfischer/pto/blob/master/src/bridge.rs#L267

**Comment by ara4n** [comment]
Hmm - ok, thanks. How are you meant to join a room without /join? Are your existing rooms meant to be autojoined by replaying some scrollback? If so, this wasn't happening - will go find some more logs in a bit if it helps.

**Comment by tdfischer** [comment]
Yeah, autojoin is supposed to happen. The intent is that there is a 1:1 mapping between Matrix and IRC states, where if you /part a channel in matrix, your IRC client will also be forced to /part a channel and vice-versa.

**Comment by ara4n** [comment]
hmmmmmmmmmm. autojoin certainly isn't happening - log attached (running against a random local testing HS called sierra).  Looks like it's trying to create a ##testing:sierra channel though with two members (matthew and matthew2) though from the tcpdump, but my xchat is barfing on it?

[autojoin-fail.txt](https://github.com/tdfischer/pto/files/107673/autojoin-fail.txt)

**Comment by tdfischer** [comment]
Interesting.

I recently pushed some commits that uses the rust logging framework with some more intensive and useful debug logging. If you rerun this with ``RUST_LOG=pto::irc=trace,pto::matrix=trace``, that'd be super and would help with filtering the log a bit more.

I've also split up your other reports into bugs #2, #3, #4, #5, and #6. Your input is *greatly* appreciated! <3

**Comment by tdfischer** [comment]
Oh! And there should be some fixes around channel aliases allowing other channels to show up now.

**Comment by ara4n** [comment]
Autojoin is still borking on latest master.  It may be xchat being thick, but the joined channels simply don't appear in the client.  Attached are logs, complete with the new RUST_LOG.

[autojoin-fail2.txt](https://github.com/tdfischer/pto/files/108981/autojoin-fail2.txt)
