### ISSUE TITLE
Concatenated cert + CA cert results in key mismatch error.

### ISSUE THREAD

**Issue by tdfischer** [tdfischer/pto#43]
Error report via jon on #pto:oob.systems:

> So I'm trying to set up PTO on one of my servers, and I concatenated my cert and intermediate CA cert together as I would for a web server... but PTO complains of cert/key mismatch. I might have slipped up somewhere, but you should be able to use an intermediate cert like that, right?

Probably needs a call to this somewhere:

http://sfackler.github.io/rust-openssl/doc/v0.7.6/openssl/ssl/struct.SslContext.html#method.set_certificate_chain_file

**Comment by jfrederickson** [comment]
No worries, was my own mistake... they did in fact not match. XD
