### ISSUE TITLE
Improved IRC parsing

### ISSUE THREAD

**Issue by tdfischer** [tdfischer/pto#5]
Split out from #1: https://github.com/tdfischer/pto/issues/1#issuecomment-175955097

Seems like there are bugs in the IRC parsing module. I understand that this may come as a shock, so please, contain your surprise.

What needs done is a fairly good test suite that parses real logs from various clients and makes sure we get the same Message structure out of it.

**Comment by vberger** [comment]
I'm willing to take a look at the IRC protocol handling part if it's ok with you, I have some experience with the client<->server protocol and all the headaches it implies. (cc #26 I guess)

**Comment by tdfischer** [comment]
Oh yes, that'd be awesome! Thanks!
